`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Project Name : INT8 CNN Accelerator
// Module Name  : accumulator
// Author       : Chetan Patil
//
// Description:
// 32-bit Signed Accumulator
// Accumulates 16-bit signed products generated by the multiplier.
//
//////////////////////////////////////////////////////////////////////////////////

module accumulator #

(
    parameter PRODUCT_WIDTH = 16,
    parameter ACC_WIDTH     = 32
)

(
    input  wire                         clk,
    input  wire                         rst,
    input  wire                         enable,

    input  wire signed [PRODUCT_WIDTH-1:0] product,

    output reg  signed [ACC_WIDTH-1:0] accumulator_out
);

//------------------------------------------------------
// Accumulator
//------------------------------------------------------

always @(posedge clk)
begin

    if(rst)

        accumulator_out <= 0;

    else if(enable)

        accumulator_out <= accumulator_out + product;

end

endmodule
